config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
    get 'settings', to: 'devise/registrations#edit'
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]

  resources :trials do
    resources :trial_presentations
  end

  resources :people do
    get 'search', on: :collection
  end

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end

  root 'trials#index'
end

app/models/trial.rb
class Trial < ApplicationRecord
  enum trial_type: [:ordinary]

  belongs_to :judge, class_name: 'User', foreign_key: :judge_id
  belongs_to :plaintiffs_lawyer, class_name: 'User', foreign_key: :plaintiffs_lawyer_id
  belongs_to :defendants_lawyer, class_name: 'User', foreign_key: :defendants_lawyer_id

  has_many :trial_people
  has_many :plaintiffs, source: :triable, source_type: 'Plaintiff', through: :trial_people
  has_many :defendants, source: :triable, source_type: 'Defendant', through: :trial_people
  has_many :trial_presentations, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validate :lawyers_are_not_equal

  after_create :create_notifications


  def attachments
    # Gather attachments from all presentations
    self.trial_presentations.map { |tp| tp.attachments }.flatten
  end

  def number_of_attachments
    self.trial_presentations.reduce(0) { |sum, tp| sum + tp.attachments.count }
  end

  private

  def lawyers_are_not_equal
    if plaintiffs_lawyer == defendants_lawyer
      # TODO: Localize strings
      errors.add(:plaintiffs_lawyer, 'Abogado defensor no puede ser igual que el abogado demandante.')
      errors.add(:defendants_lawyer, 'Abogado demandante no puede ser igual que el abogado defensor.')
    end
  end

  def recipients
    [self.plaintiffs_lawyer, self.defendants_lawyer]
  end

  def create_notifications
    recipients.each do |recipient|
      Notification.create(recipient: recipient, actor: self.judge,
        action: 'posted', notifiable: self)
    end
  end
end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  load_and_authorize_resource

  def index
    @trials = @trials.order(start_date: :desc).includes(:judge).page params[:page]

    # Search
    @q = @trials.ransack(params[:q])
    @trials = @q.result(distinct: true).order(created_at: :desc)
  end

  def show
    @trial_presentations = @trial.trial_presentations.all.includes(:user)

    @trial_presentation = @trial.trial_presentations.build
  end

  def new
    @trial = Trial.new
    @trial.trial_people.build
  end

  def create
    @trial = Trial.new(trial_params)

    respond_to do |format|
      if @trial.save
        format.html { redirect_to @trial, flash: { success: t('.success') } }
      else
        format.html { render 'new', flash: { danger: t('.error') } }
      end
    end
  end

  def edit
    @trial.trial_people.build
  end

  def update
    params[:trial][:plaintiff_ids] ||= []
    params[:trial][:defendant_ids] ||= []

    respond_to do |format|
      if @trial.update(trial_params)
        format.html { redirect_to @trial, flash: { success: t('.success') } }
      else
        format.html { render 'edit', flash: { danger: t('.error') } }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @trial.destroy
        format.html { redirect_to root_path, flash: { success: t('.success') } }
      end
    end
  end

  private

  def find_trial
    @trial = Trial.find(params[:id])
  end

  def trial_params
    params.require(:trial).permit(
      :title, :trial_type, :description, :secret, :start_date, :judge_id,
      :plaintiffs_lawyer_id, :defendants_lawyer_id,
      :plaintiff_ids => [],
      :defendant_ids => []
    )
  end
end

app/helpers/trials_helper.rb
module TrialsHelper

  def trial_notification_icon(options={})
    render_icon('inbox_document_text.png', options)
  end
end

app/views/trials/_form.html.haml
.well
  = simple_form_for(@trial) do |f|
    = render 'shared/error_messages', resource: @trial

    .form-inputs
      .row
        .col-md-12
          %legend Información General

          = f.input :title, required: true, autofocus: true
          = f.input :trial_type, required: true
          = f.input :description, required: true, input_html: { rows: 10 }

          = f.association :judge, collection: User.judges, label_method: :full_name, value_method: :id, required: true, disabled: true, selected: current_user.id
          = f.hidden_field :judge_id, value: current_user.id

          = f.input :start_date, required: true

          .checkbox
            %label
              = f.check_box :secret
              Confidencial
            = render 'shared/help_popover', title: t('popovers.confidentiality.title'), content: t('popovers.confidentiality.content')

      %br

      .row
        .col-md-12
          %legend Involucrados

        .col-md-6
          / Plaintiffs
          = f.association :plaintiffs, label_method: :full_name, value_method: :id, include_blank: false, input_html: { 'data-endpoint': search_people_path, class: 'person-search' }, required: true

          = f.association :plaintiffs_lawyer, collection: User.lawyers, label_method: :full_name, value_method: :id, input_html: { class: 'lawyer-search' }, required: true

        .col-md-6
          / Defendants
          = f.association :defendants, label_method: :full_name, value_method: :id, include_blank: false, input_html: { 'data-endpoint': search_people_path, class: 'person-search' }, required: true

          = f.association :defendants_lawyer, collection: User.lawyers, label_method: :full_name, value_method: :id, required: true, input_html: { class: 'lawyer-search' }

    .form-actions
      = f.button :submit, class: 'btn btn-success'
      = link_to 'Cancelar', root_path, class: 'btn btn-default'

app/views/trials/_meta.html.haml
%ul.list-inline.small
  %li
    = image_tag 'icons/calendar_16.png'
    %strong= l(trial.start_date, format: :long)

  %li{ 'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'Juez' }
    = link_to user_path(trial.judge) do
      = image_tag 'icons/roles/judge_16.png'
      %strong= trial.judge.full_name

  %li
    = image_tag 'icons/document_tree_16.png'
    %strong= t('action', count: trial.trial_presentations_count)

  .pull-right
    - if trial.secret
      %li
        = image_tag 'icons/lock_16.png'
        %strong Confidencial

app/views/trials/_search.html.haml
.row
  .col-md-12
    .well
      = search_form_for @q, url: trials_path do |f|
        .input-group
          = f.search_field :title_or_description_cont, placeholder: 'Buscar Juicios', class: 'form-control'
          %span.input-group-btn
            = f.button :submit, class: 'btn btn-default' do
              %span.glyphicon.glyphicon-search

app/views/trials/edit.html.haml
%h2 Editar #{@trial.title}

= render 'form'

%hr

= link_to root_path do
  %i.fa.fa-arrow-left
  Regresar

%br

app/views/trials/index.html.haml
.row
  .col-md-9
    = render 'search'

    - @trials.each do |trial|
      - if can? :read, trial
        .panel.panel-default
          .panel-body
            %h4= link_to trial.title, trial
            = render 'meta', trial: trial

            %p= trial.description

    .text-center
      = paginate @trials

  .col-md-3
    - if user_signed_in?
      .panel.panel-default
        .panel-heading
          %strong Mis Juicios
          %span.badge= current_user.trials.count

          - if can? :create, Trial
            .pull-right
              = link_to new_trial_path, class: 'btn btn-success btn-xs' do
                %span.glyphicon.glyphicon-plus
                Nuevo Juicio

        .list-group
          - current_user.trials.each do |trial|
            = link_to trial, class: 'list-group-item' do
              = image_tag 'icons/16/book.png'
              %strong= truncate(trial.title, length: 20)

app/views/trials/new.html.haml
%h2 Crear Nuevo Juicio

= render 'form'

= link_to root_path do
  %i.fa.fa-arrow-left
  Regresar

%br
%br

app/views/trials/show.html.haml
= render 'shared/error_messages', resource: @trial_presentation

%h2
  = @trial.title
  .pull-right
    = render 'shared/manage_resource', resource: @trial

.row
  .col-md-10
    = render 'trials/meta', trial: @trial

    %p= simple_format h @trial.description
    %br

    %ul.nav.nav-tabs
      %li.active
        %a{ href: '#presentations', 'data-toggle': 'tab' }
          = image_tag 'icons/document_tree_16.png'
          Actuaciones
          %span.badge= @trial.trial_presentations_count
      %li
        %a{ href: '#documents', 'data-toggle': 'tab' }
          = image_tag 'icons/file_types/page_white_text.png'
          Documentos
          %span.badge= @trial.number_of_attachments

    .tab-content
      %br
      #presentations.tab-pane.fade.active.in
        - unless @trial.trial_presentations_count.zero?
          = render @trial_presentations
        - else
          %p.text-center.small No hay actuaciones

        %br
        = render 'trial_presentations/form'
      #documents.tab-pane.fade
        = render 'trials/documents'
  .col-md-2
    %h6
      %strong Demandantes
    %ul.list-unstyled
      %li
        %small= link_to @trial.plaintiffs_lawyer.full_name, user_path(@trial.plaintiffs_lawyer)
        = image_tag 'icons/roles/lawyer_16.png', class: 'pull-right'

      - @trial.plaintiffs.each do |person|
        %li
          %small= link_to person.full_name, person_path(person)

    %hr

    %h6
      %strong Demandados
    %ul.list-unstyled
      %li
        %small= link_to @trial.defendants_lawyer.full_name, user_path(@trial.defendants_lawyer)
        = image_tag 'icons/roles/lawyer_16.png', class: 'pull-right'

      - @trial.defendants.each do |person|
        %li
          %small= link_to person.full_name, person_path(person)

    %hr

    %h6
      %strong Etiquetas

    %hr

    %h6
      %strong Progreso