config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get 'register', to: 'devise/registrations#new'
    get 'settings', to: 'devise/registrations#edit'
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]

  resources :trials do
    resources :trial_presentations
  end

  resources :people do
    get 'search', on: :collection
  end

  resources :notifications, only: [:index] do
    post :mark_as_read, on: :collection
    post :mark_as_read, on: :member
  end

  root 'trials#index'
end

app/views/shared/_alerts.html.haml
- flash.each do |name, msg|
  - case name
  - when 'alert'
    = content_tag(:div, msg, class: 'alert alert-danger alert-dismissable')
  - when 'notice'
    = content_tag(:div, msg, class: 'alert alert-success alert-dismissable')
  - when 'success'
    .alert.alert-success.alert-dismissable
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %p
        %i.glyphicon.glyphicon-ok
        = msg
  - when 'danger'
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %p
        %i.glyphicon.glyphicon-remove
        = msg

app/views/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_messages.alert.alert-danger
    %h4
      %strong Porfavor corrija los siguientes errores:
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/shared/_footer.html.haml
%hr


.pull-left
  %ul.list-inline.small.text-muted
    %li © 2017 SCSJ

.pull-right
  %ul.list-inline.small
    %li= link_to 'Terminos', '#'
    %li= link_to 'Privacidad', '#'
    %li= link_to 'Acerca', '#'

%br
%br

app/views/shared/_head.html.haml
%title SCSJ

= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js'

= stylesheet_link_tag 'application', media: 'all'
= javascript_include_tag 'application'

/ Bootstrap
= stylesheet_link_tag "https://bootswatch.com/#{BOOTSTRAP_THEME}/bootstrap.min.css"

= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'

= csrf_meta_tags

app/views/shared/_help_popover.html.haml
= image_tag 'icons/help_16.png',
  alt: 'Ayuda',
  style: 'cursor: pointer; margin-left: 10px;',
  'data-toggle': 'popover',
  'data-placement': 'right',
  title: title,
  'data-content': content

app/views/shared/_manage_resource.html.haml
.btn-toolbar
  .btn-group.btn-group-sm
    - if can? :edit, resource
      = link_to [:edit, resource], class: 'btn btn-default' do
        %span.fa.fa-pencil
        Editar
    - if can? :destroy, resource
      = link_to resource, method: :delete, data: { confirm: 'Esta seguro?' },
        class: 'btn btn-danger' do
        %span.fa.fa-trash
        Eliminar

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'SCSJ', root_path, class: 'navbar-brand'
    .navbar-collapse
      %ul.nav.navbar-nav

      %ul.nav.navbar-nav.navbar-right
        - unless user_signed_in?
          %li= link_to t('devise.registrations.new.sign_up'), register_path
          %li= link_to t('devise.sessions.new.sign_in'), login_path
        - else
          / Notifications
          %li.dropdown{ 'data-behavior': 'notifications' }
            %a.dropdown-toggle{ 'data-toggle': 'dropdown', role: 'button', 'aria-expanded': false }
              %span.glyphicon.glyphicon-bell
              %span.badge{ 'data-behavior': 'unread-count' }
              %span.caret

            %ul#notifications.dropdown-menu{ 'data-behavior': 'notification-items' }
              .container-fluid
                %li
                  %h4
                    Notificaciones
                    - unless current_user.notifications.unread.empty?
                      .pull-right
                        %li
                          = link_to mark_as_read_notifications_path, method: :post, remote: true, class: 'btn btn-default btn-xs pull-right' do
                            %span.glyphicon.glyphicon-ok
                            Marcar todas como leidas
                %li.divider

                - if current_user.notifications.empty?
                  %li
                    %p.text-center.small No hay notificaciones nuevas

          / User Links
          %li.dropdown
            %a{ :class => 'dropdown-toggle', "data-toggle" => 'dropdown', :role => 'button', "aria-expanded" => false }
              %strong= current_user.full_name
              = image_tag current_user.avatar.url(:navbar), class: 'img-circle', style: 'border: 2px solid white;'
              %span.caret
            %ul.dropdown-menu
              - if can? :read, Person
                %li
                  = link_to people_path do
                    = image_tag 'icons/group_16.png', alt: 'Personas'
                    Personas
              - if can? :create, Trial
                %li
                  = link_to new_trial_path do
                    = image_tag 'icons/application_form_add_16.png', alt: 'Crear Nuevo Juicio'
                    Crear Nuevo Juicio
              %li.divider
              %li
                = link_to user_path(current_user) do
                  = image_tag 'icons/user_16.png', alt: 'Mi Perfil'
                  Mi Perfil
              %li
                = link_to settings_path do
                  = image_tag 'icons/cog_edit_16.png', alt: 'Mi Cuenta'
                  Mi Cuenta
              %li.divider
              %li
                = link_to logout_path, method: :delete do
                  = image_tag 'icons/door_out_16.png', alt: 'Cerrar Sesión'
                  Cerrar Sesión